// Level 4 — W S O L extension
const stages = [
  "www sss aaa ddd fff sss www",
  "swd fds sws ded frf sws fdsw",
  "dews  eed rww  wsd rews  fee fee ree",
  "dswe frwa wsdf ffds fdsw fdsdf",
  "ssws ffss ssd swdr fdsw wsdf rdws",
  "sweet sweeter tweed tweet tweeted street",
  "few fewer fewest free fest fester test tester",
  "we were wet west rest wed weeds wets",
  "drew dew wedge dress deer dresser dreg",
  "jju jyj ujh jhj yjy hju yhj",
  "lol lko jlok kol jklol jujhh jklloo oljk",
  "jhy jij jjh jlol jklkjyj juj jyj jklkjyj",
  "oil oh joy lo kook yuk you yolk oily",
  "hull hulk look holy  jolly lolly hook holly",
  "ill ikill  hill jill ilk  oil oily joy lily jokily",
  "toy try fry fly why juj roy jyyj",
  "soil soul swell style well yell while style",
  "jet let yes jest wet letters lets",
  "destroy  jolly you your dirty dust yell yellow",
  "when while whole whistle will thrill",
  "tough enough louse round lion money blow",
  "silly shy sisters liked the white house",
  "the sword had a little hole",
  "willy took two dogs to the hut",
  "silly dolly lost her horse",
];

const levelConfig = {
  currentLevel  : "level4",
  nextPage      : "level5.html",
  restartPage   : "level4.html",
  caseSensitive : false,
  quoteSwap     : false,
  hasTimer      : false,
  colorNumbers  : false,
  hasNumberRow  : false,
  useLetterBoxes: false,
};
